name: Deploy to GitHub Pages
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: NUXT_APP_BASE_URL=/Starbucks-Rewards-Page/ npx nuxt build --preset github_pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
